### ISSUE TITLE
There isn't any poem

### ISSUE THREAD

**Issue by hafneraaron** [mrmclaughlin/RainbowPoem#7]
Its just a spot to put the poem without an actual poem afterwards. That should probably be fixed.

Here's some inspiration: [Top Hat](https://en.wikipedia.org/wiki/Top_Hat_(company)).

And this is an image:
![Q0](https://user-images.githubusercontent.com/50685087/57824719-feb42100-7769-11e9-8af3-a9ad0bb8c361.PNG)

**Comment by mrmclaughlin** [comment]
got it
